#!/bin/bash

#
#   Project bash script to setup working environment for FlightBookingSuggestor Project
#

export TOP=$PWD

alias top='cd $TOP'
alias b='powershell build_generic.ps1 -path "C:\Users\sluec\OneDrive\Documents\Code\Projects\FlightBookingSuggestor_v1"'
alias bt='powershell build_generic.ps1 -path "C:\Users\sluec\OneDrive\Documents\Code\Projects\FlightBookingSuggestor_v1" -t 1'
alias src='cd $TOP/src'
alias apps='cd $TOP/apps'
alias trip='cd $TOP/src/tripgen'
alias search='cd $TOP/src/search'
alias post='cd $TOP/src/post'
alias test='cd $TOP/tests'
alias tests='cd $TOP/tests'
alias inc='cd $TOP/include'
alias bin='cd $TOP/bin'
alias bind='cd $TOP/bin/Debug'
alias binr='cd $TOP/bin/Release'