/*

    Trip Itinerary Generation Object Header File

*/

#ifndef __TRIPGEN_OBJ__
#define __TRIPGEN_OBJ__

#include <string>
#include <vector>

using namespace std;

struct destination_config_t
{
    char    is_initial_cond;                ///< Flag, signifies object is the initial start OR end of trip
    char    is_starting_point;              ///< Flag, signifies object is the initial starting point of trip
    char    is_intermediate;                ///< Flag, signifies object is an intermediate destination (i.e., not start or end of trip)

    string  airport_icao;                   ///< 4-Letter/number airport ICAO identifier
    string  entry_date;                     ///< MM-DD-YYYY, date of entry into location
    string  exit_date;                      ///< MM-DD-YYYY, date of exit out of location
    
};

struct tripgen_inputs_t
{
    vector<destination_config_t> locs;      ///< Vector of locations gathered from user inputs


};

struct tripgen_outputs_t
{
    vector<string>  itineraries;            ///< Vector of possible itineraries generated by tripgen methods
};

class tripgen_obj_t
{
    public:
        tripgen_inputs_t    in;             ///< Input tripgenerator structure
        tripgen_outputs_t   out;            ///< Output tripgenerator structure

        void    inputs( tripgen_inputs_t &inp);     ///< Function to pass user inputs to private class members
        void    outputs( void );            ///< Function to populate publicly accessible class output struct
        void    init( void );               ///< Class initialization method
        void    close( void );              ///< Class closure method

    protected:


    private:


};

#endif